site_name: GEOCAT HARVESTING
site_favicon: assets/images/favicon.png
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Automation: automation.md
  - Parameters: parameters.md

theme:
  name: material
  logo: assets/images/geocat.png
  features:
    - navigation.tabs
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

extra_css:
  - assets/stylesheets/extra.css
  - https://unpkg.com/termynal@0.0.1/css/termynal.css

extra_javascript:
  - https://unpkg.com/termynal@0.0.1/js/termynal.js
  - assets/js/custom.js

repo_url: https://github.com/geoadmin/service-geocat-harvesting
repo_name: service-geocat-harvesting

markdown_extensions:
  - pymdownx.superfences