name: Build Windows EXE

on:
  push:
    branches: [ build-win-exe ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller python-dotenv
      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --onefile gui.py
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: gui-exe
          path: dist/gui.exe